# Generated by Django 4.2.21 on 2025-05-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('encargado', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('caratula', models.ImageField(upload_to='caratulas/')),
                ('total_posiciones', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('reservado', models.BooleanField(default=False)),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='rifas.rifa')),
            ],
        ),
    ]
