# Generated by Django 4.2.21 on 2025-05-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='cuenta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rifa',
            name='numerocuenta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rifa',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
